version: "3.8"

services:
    nginx:
        container_name: nginx
        restart: always
        image: nginx:alpine
        ports:
            - "8000:8000"
        volumes:
            - ./www:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - nuke

    php:
        container_name: php
        restart: always
        build:
            dockerfile: ./php-fpm/Dockerfile
            context: .
        ports:
            - "9000:9000"
        volumes:
            - ./www:/var/www
        networks:
            - nuke

    mssql:
        container_name: mssql
        user: root
        image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
        restart: always
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: mssql1Ipw
        ports:
            - "1433:1433"
        volumes:
            - mssqldb:/var/opt/mssql/data
            - ./db/logs:/var/opt/mssql/log
            - ./db/files/secrets:/var/opt/mssql/secrets
        networks:
            - nuke


volumes:
    mssqldb: {}

networks:
    nuke: {}
